name: API Automation Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '22'
          cache: maven

      - name: Run Maven Tests
        working-directory: api_restassured
        env:
          BASE_URL: ${{ vars.BASE_API_URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: mvn clean test

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_report: allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report